back:
    resource: "@BackBundle/Resources/config/routing.yml"
    prefix:   /

front_user:
    resource: "@FrontUserBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FrontUserBundle/Resources/config/routing/all.xml"
