<?php

namespace Back\BackBundle\Repository;

/**
 * InscriptionTutorielRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InscriptionTutorielRepository extends \Doctrine\ORM\EntityRepository
{
}
