<?php

namespace Back\BackBundle\Repository;

/**
 * SalleVirtuelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SalleVirtuelRepository extends \Doctrine\ORM\EntityRepository
{
}
