<?php

namespace Back\BackBundle\Repository;

/**
 * TutorielCategorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TutorielCategorieRepository extends \Doctrine\ORM\EntityRepository
{
}
